// Package notificationpbv1 contains the generated Go types for the canonical
// notification message that flows through the Pulsar Notification Pipeline.
//
// The source of truth is proto/notification/v1/notification.proto — this
// package is regenerated by `make generate` and committed. Do not edit
// notification.pb.go by hand.
//
// # Wire contract
//
// Notification is the sole wire shape carried through Apache Pulsar between
// the writer and the reader/deliverer, and it is also the request-body schema
// the writer accepts over HTTP (as protobuf bytes or as proto3 canonical JSON).
// See FR-001 in the feature spec.
//
// # Forward and backward compatibility (FR-013)
//
// This library promises forward and backward wire compatibility WITHIN A MAJOR
// VERSION. A process built against version N of this library MUST be able to
// successfully marshal/unmarshal messages produced by version N±k of the same
// major line, provided N and N±k share the same major version. Enforcement:
// pkg/notificationpb/v1/compat_test.go cross-marshals with a frozen previous
// generation under testdata/notificationpb_prev/.
//
// A breaking change (reusing a field number with a different type, removing a
// field, changing a field's type, etc.) requires a major version bump.
//
// # Adding a new push provider
//
// New providers are added by introducing a sibling message (e.g. ApnsTarget)
// and a new arm on the Notification.target oneof with a new, never-reused
// field number. See research.md §2. Reserved ranges are noted inline in the
// .proto file.
package notificationpbv1
