// Package httpserver provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package httpserver

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gorilla/mux"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for FieldErrorCode.
const (
	BeforeCreatedAt FieldErrorCode = "before-created-at"
	KeyInvalid      FieldErrorCode = "key-invalid"
	Malformed       FieldErrorCode = "malformed"
	Missing         FieldErrorCode = "missing"
	OutOfRange      FieldErrorCode = "out-of-range"
	Required        FieldErrorCode = "required"
	RequiresUrl     FieldErrorCode = "requires-url"
	TooLong         FieldErrorCode = "too-long"
	TooManyEntries  FieldErrorCode = "too-many-entries"
	UnknownArm      FieldErrorCode = "unknown-arm"
	ValueTooLong    FieldErrorCode = "value-too-long"
	WhitespaceOnly  FieldErrorCode = "whitespace-only"
)

// Valid indicates whether the value is a known member of the FieldErrorCode enum.
func (e FieldErrorCode) Valid() bool {
	switch e {
	case BeforeCreatedAt:
		return true
	case KeyInvalid:
		return true
	case Malformed:
		return true
	case Missing:
		return true
	case OutOfRange:
		return true
	case Required:
		return true
	case RequiresUrl:
		return true
	case TooLong:
		return true
	case TooManyEntries:
		return true
	case UnknownArm:
		return true
	case ValueTooLong:
		return true
	case WhitespaceOnly:
		return true
	default:
		return false
	}
}

// Content defines model for Content.
type Content struct {
	Body     string             `json:"body"`
	Data     *map[string]string `json:"data,omitempty"`
	Priority *int               `json:"priority,omitempty"`
	Title    string             `json:"title"`
}

// FieldError defines model for FieldError.
type FieldError struct {
	Code    FieldErrorCode `json:"code"`
	Field   string         `json:"field"`
	Message *string        `json:"message,omitempty"`
}

// FieldErrorCode defines model for FieldError.Code.
type FieldErrorCode string

// Meta defines model for Meta.
type Meta struct {
	// RequestId Server-generated ULID for request-scope correlation.
	RequestId string `json:"requestId"`
}

// Notification defines model for Notification.
type Notification struct {
	Content        Content    `json:"content"`
	CreatedAt      *time.Time `json:"createdAt,omitempty"`
	ExpiresAt      *time.Time `json:"expiresAt,omitempty"`
	IdempotencyKey *string    `json:"idempotencyKey,omitempty"`

	// NotificationId Server-assigned UUIDv7.
	NotificationId     *openapi_types.UUID `json:"notificationId,omitempty"`
	OriginatingService *string             `json:"originatingService,omitempty"`
	Pushover           PushoverTarget      `json:"pushover"`
}

// Problem defines model for Problem.
type Problem struct {
	Detail string `json:"detail"`

	// Errors Extension member. Populated for validation-failed problems.
	Errors   *[]FieldError `json:"errors,omitempty"`
	Instance string        `json:"instance"`

	// RequestId Extension member. Mirrors meta.requestId from successful responses.
	RequestId string `json:"requestId"`
	Status    int    `json:"status"`
	Title     string `json:"title"`

	// Type Stable URI from the documented error catalogue.
	Type string `json:"type"`
}

// PushoverTarget defines model for PushoverTarget.
type PushoverTarget struct {
	DeviceName     *string `json:"deviceName,omitempty"`
	Sound          *string `json:"sound,omitempty"`
	Url            *string `json:"url,omitempty"`
	UrlTitle       *string `json:"urlTitle,omitempty"`
	UserOrGroupKey string  `json:"userOrGroupKey"`
}

// SubmitNotificationSuccess defines model for SubmitNotificationSuccess.
type SubmitNotificationSuccess struct {
	Data struct {
		AcceptedAt     time.Time          `json:"acceptedAt"`
		NotificationId openapi_types.UUID `json:"notificationId"`
	} `json:"data"`
	Meta Meta `json:"meta"`
}

// AuthenticationRequired defines model for AuthenticationRequired.
type AuthenticationRequired = Problem

// IdempotencyConflict defines model for IdempotencyConflict.
type IdempotencyConflict = Problem

// Internal defines model for Internal.
type Internal = Problem

// SubstrateUnavailable defines model for SubstrateUnavailable.
type SubstrateUnavailable = Problem

// UnsupportedContentType defines model for UnsupportedContentType.
type UnsupportedContentType = Problem

// ValidationFailed defines model for ValidationFailed.
type ValidationFailed = Problem

// SubmitNotificationParams defines parameters for SubmitNotification.
type SubmitNotificationParams struct {
	// IdempotencyKey Optional client-supplied idempotency key. Maximum 128 characters.
	// When repeated within the configured window with an identical payload,
	// the request is de-duplicated and the original notification_id is
	// returned.
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// SubmitNotificationJSONRequestBody defines body for SubmitNotification for application/json ContentType.
type SubmitNotificationJSONRequestBody = Notification

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Submit a notification for delivery.
	// (POST /notifications)
	SubmitNotification(w http.ResponseWriter, r *http.Request, params SubmitNotificationParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// SubmitNotification operation middleware
func (siw *ServerInterfaceWrapper) SubmitNotification(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params SubmitNotificationParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitNotification(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/notifications", wrapper.SubmitNotification).Methods("POST")

	return r
}

type AuthenticationRequiredApplicationProblemPlusJSONResponse Problem

type IdempotencyConflictApplicationProblemPlusJSONResponse Problem

type InternalApplicationProblemPlusJSONResponse Problem

type SubstrateUnavailableApplicationProblemPlusJSONResponse Problem

type UnsupportedContentTypeApplicationProblemPlusJSONResponse Problem

type ValidationFailedApplicationProblemPlusJSONResponse Problem

type SubmitNotificationRequestObject struct {
	Params   SubmitNotificationParams
	JSONBody *SubmitNotificationJSONRequestBody
	Body     io.Reader
}

type SubmitNotificationResponseObject interface {
	VisitSubmitNotificationResponse(w http.ResponseWriter) error
}

type SubmitNotification202JSONResponse SubmitNotificationSuccess

func (response SubmitNotification202JSONResponse) VisitSubmitNotificationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type SubmitNotification400ApplicationProblemPlusJSONResponse struct {
	ValidationFailedApplicationProblemPlusJSONResponse
}

func (response SubmitNotification400ApplicationProblemPlusJSONResponse) VisitSubmitNotificationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SubmitNotification401ApplicationProblemPlusJSONResponse struct {
	AuthenticationRequiredApplicationProblemPlusJSONResponse
}

func (response SubmitNotification401ApplicationProblemPlusJSONResponse) VisitSubmitNotificationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SubmitNotification409ApplicationProblemPlusJSONResponse struct {
	IdempotencyConflictApplicationProblemPlusJSONResponse
}

func (response SubmitNotification409ApplicationProblemPlusJSONResponse) VisitSubmitNotificationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type SubmitNotification415ApplicationProblemPlusJSONResponse struct {
	UnsupportedContentTypeApplicationProblemPlusJSONResponse
}

func (response SubmitNotification415ApplicationProblemPlusJSONResponse) VisitSubmitNotificationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(415)

	return json.NewEncoder(w).Encode(response)
}

type SubmitNotification500ApplicationProblemPlusJSONResponse struct {
	InternalApplicationProblemPlusJSONResponse
}

func (response SubmitNotification500ApplicationProblemPlusJSONResponse) VisitSubmitNotificationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type SubmitNotification503ApplicationProblemPlusJSONResponse struct {
	SubstrateUnavailableApplicationProblemPlusJSONResponse
}

func (response SubmitNotification503ApplicationProblemPlusJSONResponse) VisitSubmitNotificationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Submit a notification for delivery.
	// (POST /notifications)
	SubmitNotification(ctx context.Context, request SubmitNotificationRequestObject) (SubmitNotificationResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// SubmitNotification operation middleware
func (sh *strictHandler) SubmitNotification(w http.ResponseWriter, r *http.Request, params SubmitNotificationParams) {
	var request SubmitNotificationRequestObject

	request.Params = params
	if strings.HasPrefix(r.Header.Get("Content-Type"), "application/json") {

		var body SubmitNotificationJSONRequestBody
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
		request.JSONBody = &body

	}
	if strings.HasPrefix(r.Header.Get("Content-Type"), "application/x-protobuf") {
		request.Body = r.Body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SubmitNotification(ctx, request.(SubmitNotificationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SubmitNotification")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SubmitNotificationResponseObject); ok {
		if err := validResponse.VisitSubmitNotificationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xYbW/byPH/KgP+70WCIyXZvuBy+r9ycs7VvSQ2/NAAjdJkxR2Je1nOsrtL2WogoB+i",
	"n7CfpJhdiqIk2nKBIq9skZznmd88fEtyU1aGkLxLxt8Si64y5DD8OK19geRVLrwydIV/r5VFyW9yQx7J",
	"87+iqnTzxbCyZqqx/PEPZ4jfubzAUvB/P1icJePk/4YbccP41g0vI1WyWq3SRKLLraqYXTJO3innFM3B",
	"WFC0EFpJmKKwaMGbr0iDZJUm5xLLynikfPna0Eyr3H9PFW8KBLVRAb7iEu6EA4dIcKd8AQKkWqCdI3mo",
	"xFIbIUGRUxLBFwh3iqS5i6aQR0tCf0/9bwnvK8w9SnBoF2gBrTU26HNdT523wuMtiYVQWkw1fk/dLmvt",
	"hAXlgIyHvLYWyesliDzHynNiVPVUK1eg+3/ItWIPu8LUWoJFb5fBiFtydVUZ61G+jnrfLKvvakYjNmO5",
	"wRhUvkALXaEsDMhsP7zPKmu8mdazYMlfuADCmzdC6e9biVz96DxMjVzCLIiHXJAhlQudRQawaBUcJMyi",
	"4ctiX2/0rKyp0HoVQYYZ8t9S3L9FmvsiGR+Njn9Kk1JR+yBNfIhZ4rxVNGdnSOGDPUJKxRKFvtzi2+H3",
	"4ui4h0Ep7rsUJ5tvzPQPzD1/U1llrPJBQYkzUWufjEeBVpV1mYyPg57x/2zDQZHHOVpm4ZWPRdNR6PjF",
	"6IB9qzSxLd5+bJik0VmfehR9o1DLMy7cfQ/nRgYFkFjLjxvGaeKNybSheZImd4Xy6CqRY2ZIL5M0MbXP",
	"zCyzguYsuxR6ZmzZ0pWClhmStywmTb7iMmswOkmThdA1Zh32ZUTyJE1q+krmjjJhy6S10mW11WwgzozF",
	"LLcoPMpM+I61m9DN2Fo2aT+o6JyYY8+7HY9GFml0Tp9H32HMr21f2lgG5zJmRLdCrgN6ZnMkZMiUcPv2",
	"/FeYGQsNUeZyUyHkxlrUTZUcCvxGXp+O741Xs6bk++LeltxjRb+uzFWaNG4/DTQcbOGTMVcaZl6VGMIl",
	"5AWnx9jbGntCg/cVh/MRFlTrppE8wKLTTX/HPWw4fvkEFtRxzCOxEs6pOXGobs9/XfzM4WhVruuQyAcN",
	"NlbNFQnuRsxV5Rjz5ABZVbvCLNAehOTmuxth5+j38mMd4w7DvkRZA/tejkj0QuneUgpjgNv33dm9R3LK",
	"EJRYTtEO4NJUtQ4pz9m+aQJZ0yeaZuTYv8pj6Q4Z3UGzVWuNsFYsQ36Q84Jy7NX6kQLdV/ydCjZCiV4M",
	"WkqYWVOCq/McnZvVGtqhuKde08R54WvXUaYP/PeofDOD7OSl57SG26vzqATPh9LkdYnE7g0hgVx4oc28",
	"xu18teogmoS3adtNGs3TdRZ0XJseQJ6dtOzJK66E96Lcb3375VsJz3NvMk7+9vE0+6vI/jHKfvmcffrx",
	"h15/m5rkE7juEXKH6YJS9NjunPAUNjc9Pf1oNHoKsUN7YX+zpq72se1keyrgn72u6XXMTqh3BPXF8Lqe",
	"lsp3e8h1zPmecIq+ZhjH8Ef7xROQeRdxH7drhz7tKtFnZNm08cfgJrT6XUHB5IZ+nzHnIeY1z4bXzKWZ",
	"ZcNuymtzb2l7lW+trw54F8QGcATMlEawOEOLlKOE6RI+XJ3fnF19fnV2enV29fnm4vez99ef35y/PePa",
	"D/qzVpHpxneF91Uc4hXNzL4uf7q5uYTTy3PA+8q4KCmsolZ5tDBVJOwSzCw8rMISlgXHR79nlapQK8LB",
	"hG4K5VqI4uWGSUTtC56bhVcLHnjIW5F7ePbmKhsdvXw+gFfGF+HLuHJOqBAkNVpwvp46eKYIvqhmGR5G",
	"rYZsVPx8+OU5CJKNdlOtcvjNNPvfhLSaWlY/MKm+zofdlIkfBQYWYTOrNWirXAjCYEITumpQn1cehS4Q",
	"CH0nlg7+fH3xHizOhZUanVt7qoFMaJoycDTGEwLI4Pj+ftNGoHYIX3a3vy+tTd8499LQlVaAtEBtKtaJ",
	"GYWu+Bir7ub3BSq0cPXmNfzy04ufBxNqwb/drbvlD5dNXOHf//wXfIjJcHp5zvM8WhdzZzQ4GozC4FMh",
	"iUol4+RkMBqcJAGsilAHWy6PcGKc38/D01C7DsRmldxWqBnnQRE0O/N6IQZjQxgm9Cw8OumwCOEpRVWF",
	"01GMjRMlrtk9H8AFrRt8yq8n1KR+e08IRGvx3kDjLg6RRV9bYq27gZrQOlIh/kIRSw/VsJ4yu175rGSM",
	"BwNqi4Y9mBz8akWJHnka+7jrw4sqbr9N/meu5mRAuXuUGsC7uLTC0fFLyAvBJYnWDSb0oUACi1UY/sPN",
	"SlHQPDc0U/PahqckzV1z0CJmHg6Den3RSifULQEGBcxkHfMSZZvbzbisd50Byk0oehYbzyg2r0AhA7RR",
	"mCW6176MG1vaOW3srgm7neRTO9W8ao4OD1xP/ruryVa0GHT7TzjbDPePiAdKwKFVQitGa+HaMpjQM4cY",
	"f25V3XBxtPV7ED55PoCbFucnJJHXXxeBT5E3m1Jh30lw3ta5Z4H8ItTV1MhljE/buGO/6GndWy2VJ6Lw",
	"oHNhPh4d/8/C8PA403PO2nLxeoQISbpGAAlrd6yPoOEG99No9JAirWXDvUNdIDw6TPjAxT2Q/3KYvO8U",
	"zrRHLw7TPnAmXaXJi6eY3J6uA8HJYYLe23J3rgpY152oPn7iCnZ1WXK2rbESxBaUhBVUolYLDPffp3AM",
	"Q0Uftr41XI4SA66Xcc8OW0SYsMbDoeYPCuP8+OXo5ShZfVr9JwAA///ojxKgURkAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
