// Canonical notification message schema for the pulsar-notifcation-pipeline.
//
// This file is the SINGLE SOURCE OF TRUTH for the wire contract carried through Apache
// Pulsar and for the proto3-canonical-JSON representation accepted by the writer's HTTP
// API. See specs/001-notification-pipeline/data-model.md for field-level rules.
//
// Forward/backward wire compatibility within a major version is mandatory (FR-013).
// Adding a new push provider = adding a new sibling message + a new `target` oneof arm
// with a new, never-reused field number. See research.md §2.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/notification/v1/prev/notification.proto

// Frozen previous-generation copy, used ONLY by the wire-compat test in
// pkg/notificationpb/v1/. Protobuf package is renamed so the file descriptor
// registers under a distinct name and does not collide with the current
// notification.v1 package. See pkg/notificationpb/v1/prev/doc.go.

package notificationpbv1prev

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Notification is the canonical pipeline message. The writer assigns the
// server-controlled fields (notification_id, created_at, originating_service) and
// rejects requests where a caller sets them.
type Notification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-assigned UUIDv7. Stable identifier across the pipeline.
	NotificationId string `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	// Server-assigned moment of writer acceptance.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Caller-supplied expiry. If set and in the past at consume time, the message is
	// dropped with terminal status `expired`.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Server-assigned; derived from the authenticated caller's bearer token.
	OriginatingService string `protobuf:"bytes,4,opt,name=originating_service,json=originatingService,proto3" json:"originating_service,omitempty"`
	// Caller-supplied idempotency key (optional). When repeated within the writer's
	// idempotency window with the same payload, dispatch is de-duplicated.
	IdempotencyKey string `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Common, provider-agnostic payload.
	Content *Content `protobuf:"bytes,10,opt,name=content,proto3" json:"content,omitempty"`
	// Per-provider addressing and options. Exactly one arm must be set. Adding a new
	// arm is the normal way to add a new push provider.
	//
	// Types that are valid to be assigned to Target:
	//
	//	*Notification_Pushover
	Target        isNotification_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_proto_notification_v1_prev_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_prev_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_prev_notification_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *Notification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Notification) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Notification) GetOriginatingService() string {
	if x != nil {
		return x.OriginatingService
	}
	return ""
}

func (x *Notification) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Notification) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Notification) GetTarget() isNotification_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *Notification) GetPushover() *PushoverTarget {
	if x != nil {
		if x, ok := x.Target.(*Notification_Pushover); ok {
			return x.Pushover
		}
	}
	return nil
}

type isNotification_Target interface {
	isNotification_Target()
}

type Notification_Pushover struct {
	Pushover *PushoverTarget `protobuf:"bytes,100,opt,name=pushover,proto3,oneof"`
}

func (*Notification_Pushover) isNotification_Target() {}

// Content is the provider-agnostic, user-visible payload.
type Content struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1..250 UTF-8 characters. No leading/trailing whitespace.
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// 1..1024 UTF-8 characters.
	Body string `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	// [-2, 2]. 0 = normal. Providers map down to their native ranges.
	Priority int32 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	// Caller-supplied key/value metadata forwarded to the client (for deep linking, etc.).
	// <= 32 entries; keys match [A-Za-z_][A-Za-z0-9_]* and are <= 64 chars; values <= 512.
	Data          map[string]string `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_proto_notification_v1_prev_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_prev_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_prev_notification_proto_rawDescGZIP(), []int{1}
}

func (x *Content) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Content) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Content) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Content) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

// PushoverTarget carries Pushover-specific addressing and optional per-message
// delivery hints. The Pushover application API token (sender credential) is NOT a
// per-message field — it is deliverer-level config loaded from the environment.
type PushoverTarget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pushover user or group key. 30 alphanumeric characters. REQUIRED.
	UserOrGroupKey string `protobuf:"bytes,1,opt,name=user_or_group_key,json=userOrGroupKey,proto3" json:"user_or_group_key,omitempty"`
	// Specific device name. 1..25 chars; [A-Za-z0-9_-]+. Empty = all of the recipient's
	// devices.
	DeviceName string `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Pushover sound identifier. <= 25 chars. Empty = Pushover default.
	Sound string `protobuf:"bytes,3,opt,name=sound,proto3" json:"sound,omitempty"`
	// Supplementary URL shown with the message. Valid absolute URL, <= 512 chars.
	Url string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	// Text for `url`. <= 100 chars. If set, `url` MUST also be set.
	UrlTitle      string `protobuf:"bytes,5,opt,name=url_title,json=urlTitle,proto3" json:"url_title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushoverTarget) Reset() {
	*x = PushoverTarget{}
	mi := &file_proto_notification_v1_prev_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushoverTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushoverTarget) ProtoMessage() {}

func (x *PushoverTarget) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_prev_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushoverTarget.ProtoReflect.Descriptor instead.
func (*PushoverTarget) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_prev_notification_proto_rawDescGZIP(), []int{2}
}

func (x *PushoverTarget) GetUserOrGroupKey() string {
	if x != nil {
		return x.UserOrGroupKey
	}
	return ""
}

func (x *PushoverTarget) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *PushoverTarget) GetSound() string {
	if x != nil {
		return x.Sound
	}
	return ""
}

func (x *PushoverTarget) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PushoverTarget) GetUrlTitle() string {
	if x != nil {
		return x.UrlTitle
	}
	return ""
}

var File_proto_notification_v1_prev_notification_proto protoreflect.FileDescriptor

const file_proto_notification_v1_prev_notification_proto_rawDesc = "" +
	"\n" +
	"-proto/notification/v1/prev/notification.proto\x12\x13notification.v1prev\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x03\n" +
	"\fNotification\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12/\n" +
	"\x13originating_service\x18\x04 \x01(\tR\x12originatingService\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x126\n" +
	"\acontent\x18\n" +
	" \x01(\v2\x1c.notification.v1prev.ContentR\acontent\x12A\n" +
	"\bpushover\x18d \x01(\v2#.notification.v1prev.PushoverTargetH\x00R\bpushoverB\b\n" +
	"\x06target\"\xc4\x01\n" +
	"\aContent\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12:\n" +
	"\x04data\x18\x04 \x03(\v2&.notification.v1prev.Content.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa1\x01\n" +
	"\x0ePushoverTarget\x12)\n" +
	"\x11user_or_group_key\x18\x01 \x01(\tR\x0euserOrGroupKey\x12\x1f\n" +
	"\vdevice_name\x18\x02 \x01(\tR\n" +
	"deviceName\x12\x14\n" +
	"\x05sound\x18\x03 \x01(\tR\x05sound\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x1b\n" +
	"\turl_title\x18\x05 \x01(\tR\burlTitleBhZfgithub.com/michaelpeterswa/pulsar-notifcation-pipeline/pkg/notificationpb/v1/prev;notificationpbv1prevb\x06proto3"

var (
	file_proto_notification_v1_prev_notification_proto_rawDescOnce sync.Once
	file_proto_notification_v1_prev_notification_proto_rawDescData []byte
)

func file_proto_notification_v1_prev_notification_proto_rawDescGZIP() []byte {
	file_proto_notification_v1_prev_notification_proto_rawDescOnce.Do(func() {
		file_proto_notification_v1_prev_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_notification_v1_prev_notification_proto_rawDesc), len(file_proto_notification_v1_prev_notification_proto_rawDesc)))
	})
	return file_proto_notification_v1_prev_notification_proto_rawDescData
}

var file_proto_notification_v1_prev_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_notification_v1_prev_notification_proto_goTypes = []any{
	(*Notification)(nil),          // 0: notification.v1prev.Notification
	(*Content)(nil),               // 1: notification.v1prev.Content
	(*PushoverTarget)(nil),        // 2: notification.v1prev.PushoverTarget
	nil,                           // 3: notification.v1prev.Content.DataEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_proto_notification_v1_prev_notification_proto_depIdxs = []int32{
	4, // 0: notification.v1prev.Notification.created_at:type_name -> google.protobuf.Timestamp
	4, // 1: notification.v1prev.Notification.expires_at:type_name -> google.protobuf.Timestamp
	1, // 2: notification.v1prev.Notification.content:type_name -> notification.v1prev.Content
	2, // 3: notification.v1prev.Notification.pushover:type_name -> notification.v1prev.PushoverTarget
	3, // 4: notification.v1prev.Content.data:type_name -> notification.v1prev.Content.DataEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_notification_v1_prev_notification_proto_init() }
func file_proto_notification_v1_prev_notification_proto_init() {
	if File_proto_notification_v1_prev_notification_proto != nil {
		return
	}
	file_proto_notification_v1_prev_notification_proto_msgTypes[0].OneofWrappers = []any{
		(*Notification_Pushover)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_notification_v1_prev_notification_proto_rawDesc), len(file_proto_notification_v1_prev_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_notification_v1_prev_notification_proto_goTypes,
		DependencyIndexes: file_proto_notification_v1_prev_notification_proto_depIdxs,
		MessageInfos:      file_proto_notification_v1_prev_notification_proto_msgTypes,
	}.Build()
	File_proto_notification_v1_prev_notification_proto = out.File
	file_proto_notification_v1_prev_notification_proto_goTypes = nil
	file_proto_notification_v1_prev_notification_proto_depIdxs = nil
}
